name: PermissionColors
main: net.acomputerdog.PermissionColors.PluginPermissionColors
version: 0.3.2
description: Use a permissions structure to color-code player names.
author: acomputerdog

commands:
  permissioncolors:
    description: Main PermissionColors command
    permission: permissioncolors.command
    usage: /permissioncolors <command>
    aliases: [permcolors, permcol, pc]

permissions:
  permissioncolors.command:
    default: true
    description: Use main permissioncolors command
  permissioncolors.command.reload:
    default: op
    description: Use reload subcommand
  permissioncolors.color.black:
    default: false
  permissioncolors.color.dark_blue:
    default: false
  permissioncolors.color.dark_green:
    default: false
  permissioncolors.color.dark_aqua:
    default: false
  permissioncolors.color.dark_red:
    default: false
  permissioncolors.color.dark_purple:
    default: false
  permissioncolors.color.gold:
    default: false
  permissioncolors.color.grey:
    default: false
  permissioncolors.color.dark_grey:
    default: false
  permissioncolors.color.blue:
    default: false
  permissioncolors.color.green:
    default: false
  permissioncolors.color.aqua:
    default: false
  permissioncolors.color.red:
    default: false
  permissioncolors.color.light_purple:
    default: false
  permissioncolors.color.yellow:
    default: false
  permissioncolors.format.scrambled:
    default: false
  permissioncolors.format.bold:
    default: false
  permissioncolors.format.strikethrough:
    default: false
  permissioncolors.format.underline:
    default: false
  permissioncolors.format.italic:
    default: false